NMPC.internals:
  dT: 0.05 # This is a comment
  N: 25 # Horizon
  Q: # Stage cost
    - 15 # x
    - 15 # y
    - 0.5 # psi heading angle
    - 0.01 # delta steering angle
  R:
    - 0.05 # velocity
    - 0.5 # steering rate
  only_euler: False #use rk4

NMPC.externals:
  u_ref:
    - 20 # v (m/s)
    - 0 # phi steering rate (rad/s2)
  bounds:
    x:
      - [-50000, -50000, -3.14, -3.14] #lbx
      - [50000, 50000, 3.14, 3.14] #ubx
    u:
      - [0, -3.14] #lbu
      - [24, 3.14] #ubu
    g:
      - [0, 0, 0, 0] #lbg
      - [0, 0, 0, 0] #ubg
  vehicle:
    model_type: fac # (rac, fac, cog) rear axle center
    L: 4 # vehicle length
    Lr: 2.3 # distance from rac to cog

NMPC.environment:
  world_map: Town05 #example carla map
  trajectory:
    wps_file: ./maps/carla_town05_02012024.wps #wps file name env_mapname_date.wps (npy form)
    wps_factor: 4 # reduce the total number of waypoints by a facotr of 4
  run_environment: Simulation # or Carla simulation

