NMPC.internals:
  dT: 0.05 # This is a comment
  N: 25 # Horizon
  Q: # Stage cost
    - 15 # x
    - 15 # y
    - 0.5 # psi heading angle
    - 0.01 # delta steering angle
  R:
    - 0.05 # velocity
    - 0.5 # steering rate
