NMPC.internals:
  dT: 0.05 # This is a comment
  N: 25 # Horizon
  Q: # Stage cost
    - 15 # x
    - 15 # y
    - 0.5 # psi heading angle
    - 0.01 # delta steering angle
  R:
    - 0.05 # velocity
    - 0.5 # steering rate

NMPC.externals:
  u_ref:
    - 20 # v (m/s)
    - 0 # phi steering rate (rad/s2)
  bounds:
    x:
      - [1, 2, 3, 4] #lbx
      - [1, 2, 3, 4] #ubx
    u:
      - [1, 2] #lbu
      - [1, 2] #ubu
    g:
      - [0, 0, 0, 0] #lbg
      - [0, 0, 0, 0] #ubg
  vehicle:
    model_type: rac # (rac, fac, cog) rear axle center
    L: 4 # vehicle length
    Lr: 2.3 # distance from rac to cog

NMPC.environment:
  map: Town05 #example carla map
  wps_file: ./maps/town05_wps_02012024.npy #wps file name env_mapname_date.npy
  wps_factor: 4 # reduce the total number of waypoints by a facotr of 4
  run_environment: Simulation # or Carla simulation

